apps/customer/forms.py
import string
import random

from django import forms
from django.conf import settings
from django.contrib.auth import forms as auth_forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sites.models import get_current_site
from django.core.exceptions import ValidationError
from django.utils.http import is_safe_url
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import pgettext_lazy

from oscar.core.loading import get_profile_class, get_class, get_model
from oscar.core.compat import get_user_model, existing_user_fields
from oscar.apps.customer.utils import get_password_reset_url, normalise_email
from oscar.core.validators import password_validators


Dispatcher = get_class('customer.utils', 'Dispatcher')
CommunicationEventType = get_model('customer', 'communicationeventtype')
ProductAlert = get_model('customer', 'ProductAlert')
User = get_user_model()


def generate_username():
    # Python 3 uses ascii_letters. If not available, fallback to letters
    try:
        letters = string.ascii_letters
    except AttributeError:
        letters = string.letters
    uname = ''.join([random.choice(letters + string.digits + '_')
                     for i in range(30)])
    try:
        User.objects.get(username=uname)
        return generate_username()
    except User.DoesNotExist:
        return uname


class PasswordResetForm(auth_forms.PasswordResetForm):
    """
    This form takes the same structure as its parent from django.contrib.auth
    """
    communication_type_code = "PASSWORD_RESET"

    def save(self, domain_override=None, use_https=False, request=None,
             **kwargs):
        """
        Generates a one-use only link for resetting password and sends to the
        user.
        """
        site = get_current_site(request)
        if domain_override is not None:
            site.domain = site.name = domain_override
        email = self.cleaned_data['email']
        active_users = User._default_manager.filter(
            email__iexact=email, is_active=True)
        for user in active_users:
            reset_url = self.get_reset_url(site, request, user, use_https)
            ctx = {
                'user': user,
                'site': site,
                'reset_url': reset_url}
            messages = CommunicationEventType.objects.get_and_render(
                code=self.communication_type_code, context=ctx)
            Dispatcher().dispatch_user_messages(user, messages)

    def get_reset_url(self, site, request, user, use_https):
        # the request argument isn't used currently, but implementors might
        # need it to determine the correct subdomain
        reset_url = "%s://%s%s" % (
            'https' if use_https else 'http',
            site.domain,
            get_password_reset_url(user))

        return reset_url


class SetPasswordForm(auth_forms.SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(SetPasswordForm, self).__init__(*args, **kwargs)
        # Enforce password validations for the new password
        self.fields['new_password1'].validators += password_validators


class PasswordChangeForm(auth_forms.PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        # Enforce password validations for the new password
        self.fields['new_password1'].validators += password_validators


class EmailAuthenticationForm(AuthenticationForm):
    """
    Extends the standard django AuthenticationForm, to support 75 character
    usernames. 75 character usernames are needed to support the EmailOrUsername
    auth backend.
    """
    username = forms.EmailField(label=_('Email address'))
    redirect_url = forms.CharField(
        widget=forms.HiddenInput, required=False)

    def __init__(self, host, *args, **kwargs):
        self.host = host
        super(EmailAuthenticationForm, self).__init__(*args, **kwargs)

    def clean_redirect_url(self):
        url = self.cleaned_data['redirect_url'].strip()
        if url and is_safe_url(url, self.host):
            return url


class ConfirmPasswordForm(forms.Form):
    """
    Extends the standard django AuthenticationForm, to support 75 character
    usernames. 75 character usernames are needed to support the EmailOrUsername
    auth backend.
    """
    password = forms.CharField(label=_("Password"), widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        super(ConfirmPasswordForm, self).__init__(*args, **kwargs)
        self.user = user

    def clean_password(self):
        password = self.cleaned_data['password']
        if not self.user.check_password(password):
            raise forms.ValidationError(
                _("The entered password is not valid!"))
        return password


class EmailUserCreationForm(forms.ModelForm):
    email = forms.EmailField(label=_('Email address'))
    password1 = forms.CharField(
        label=_('Password'), widget=forms.PasswordInput,
        validators=password_validators)
    password2 = forms.CharField(
        label=_('Confirm password'), widget=forms.PasswordInput)
    redirect_url = forms.CharField(
        widget=forms.HiddenInput, required=False)

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, host=None, *args, **kwargs):
        self.host = host
        super(EmailUserCreationForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        """
        Checks for existing users with the supplied email address.
        """
        email = normalise_email(self.cleaned_data['email'])
        if User._default_manager.filter(email__iexact=email).exists():
            raise forms.ValidationError(
                _("A user with that email address already exists"))
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1', '')
        password2 = self.cleaned_data.get('password2', '')
        if password1 != password2:
            raise forms.ValidationError(
                _("The two password fields didn't match."))
        return password2

    def clean_redirect_url(self):
        url = self.cleaned_data['redirect_url'].strip()
        if url and is_safe_url(url, self.host):
            return url
        return settings.LOGIN_REDIRECT_URL

    def save(self, commit=True):
        user = super(EmailUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])

        if 'username' in [f.name for f in User._meta.fields]:
            user.username = generate_username()
        if commit:
            user.save()
        return user


class OrderSearchForm(forms.Form):
    date_from = forms.DateField(
        required=False, label=pgettext_lazy("start date", "From"))
    date_to = forms.DateField(
        required=False, label=pgettext_lazy("end date", "To"))
    order_number = forms.CharField(required=False, label=_("Order number"))

    def clean(self):
        if self.is_valid() and not any([self.cleaned_data['date_from'],
                                        self.cleaned_data['date_to'],
                                        self.cleaned_data['order_number']]):
            raise forms.ValidationError(_("At least one field is required."))
        return super(OrderSearchForm, self).clean()

    def description(self):
        """
        Uses the form's data to build a useful description of what orders
        are listed.
        """
        if not self.is_bound or not self.is_valid():
            return _('All orders')
        else:
            date_from = self.cleaned_data['date_from']
            date_to = self.cleaned_data['date_to']
            order_number = self.cleaned_data['order_number']
            return self._orders_description(date_from, date_to, order_number)

    def _orders_description(self, date_from, date_to, order_number):
        if date_from and date_to:
            if order_number:
                desc = _('Orders placed between %(date_from)s and '
                         '%(date_to)s and order number containing '
                         '%(order_number)s')
            else:
                desc = _('Orders placed between %(date_from)s and '
                         '%(date_to)s')
        elif date_from:
            if order_number:
                desc = _('Orders placed since %(date_from)s and '
                         'order number containing %(order_number)s')
            else:
                desc = _('Orders placed since %(date_from)s')
        elif date_to:
            if order_number:
                desc = _('Orders placed until %(date_to)s and '
                         'order number containing %(order_number)s')
            else:
                desc = _('Orders placed until %(date_to)s')
        elif order_number:
            desc = _('Orders with order number containing %(order_number)s')
        else:
            return None
        params = {
            'date_from': date_from,
            'date_to': date_to,
            'order_number': order_number,
        }
        return desc % params

    def get_filters(self):
        date_from = self.cleaned_data['date_from']
        date_to = self.cleaned_data['date_to']
        order_number = self.cleaned_data['order_number']
        kwargs = {}
        if date_from and date_to:
            kwargs['date_placed__range'] = [date_from, date_to]
        elif date_from and not date_to:
            kwargs['date_placed__gt'] = date_from
        elif not date_from and date_to:
            kwargs['date_placed__lt'] = date_to
        if order_number:
            kwargs['number__contains'] = order_number
        return kwargs


class UserForm(forms.ModelForm):

    def __init__(self, user, *args, **kwargs):
        self.user = user
        kwargs['instance'] = user
        super(UserForm, self).__init__(*args, **kwargs)
        if 'email' in self.fields:

apps/customer/__init__.py
default_app_config = 'oscar.apps.customer.config.CustomerConfig'

apps/customer/alerts/views.py
from django.http import Http404
from django.views import generic
from oscar.core.loading import get_model
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django import http

from oscar.core.loading import get_class
from oscar.apps.customer.alerts import utils
from oscar.apps.customer.mixins import PageTitleMixin

Product = get_model('catalogue', 'Product')
ProductAlert = get_model('customer', 'ProductAlert')
ProductAlertForm = get_class('customer.forms', 'ProductAlertForm')


class ProductAlertListView(PageTitleMixin, generic.ListView):
    model = ProductAlert
    template_name = 'customer/alerts/alert_list.html'
    context_object_name = 'alerts'
    page_title = _('Product Alerts')
    active_tab = 'alerts'

    def get_queryset(self):
        return ProductAlert.objects.select_related().filter(
            user=self.request.user,
            date_closed=None,
        )


class ProductAlertCreateView(generic.CreateView):
    """
    View to create a new product alert based on a registered user
    or an email address provided by an anonymous user.
    """
    model = ProductAlert
    form_class = ProductAlertForm
    template_name = 'customer/alerts/form.html'

    def get_context_data(self, **kwargs):
        ctx = super(ProductAlertCreateView, self).get_context_data(**kwargs)
        ctx['product'] = self.product
        ctx['alert_form'] = ctx.pop('form')
        return ctx

    def get(self, request, *args, **kwargs):
        product = get_object_or_404(Product, pk=self.kwargs['pk'])
        return http.HttpResponseRedirect(product.get_absolute_url())

    def post(self, request, *args, **kwargs):
        self.product = get_object_or_404(Product, pk=self.kwargs['pk'])
        return super(ProductAlertCreateView, self).post(request, *args,
                                                        **kwargs)

    def get_form_kwargs(self):
        kwargs = super(ProductAlertCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['product'] = self.product
        return kwargs

    def form_valid(self, form):
        response = super(ProductAlertCreateView, self).form_valid(form)
        if self.object.is_anonymous:
            utils.send_alert_confirmation(self.object)
        return response

    def get_success_url(self):
        if self.object.user:
            msg = _("An alert has been created")
        else:
            msg = _("A confirmation email has been sent to %s") \
                % self.object.email
        messages.success(self.request, msg)
        return self.object.product.get_absolute_url()


class ProductAlertConfirmView(generic.RedirectView):
    permanent = False

    def get(self, request, *args, **kwargs):
        self.alert = get_object_or_404(ProductAlert, key=kwargs['key'])
        self.update_alert()
        return super(ProductAlertConfirmView, self).get(request, *args,
                                                        **kwargs)

    def update_alert(self):
        if self.alert.can_be_confirmed:
            self.alert.confirm()
            messages.success(self.request, _("Your stock alert is now active"))
        else:
            messages.error(self.request, _("Your stock alert cannot be"
                                           " confirmed"))

    def get_redirect_url(self, **kwargs):
        return self.alert.product.get_absolute_url()


class ProductAlertCancelView(generic.RedirectView):
    """
    This function allows canceling alerts by supplying the key (used for
    anonymously created alerts) or the pk (used for alerts created by a
    authenticated user).

    Specifying the redirect url is possible by supplying a 'next' GET
    parameter.  It defaults to showing the associated product page.
    """
    permanent = False

    def get(self, request, *args, **kwargs):
        if 'key' in kwargs:
            self.alert = get_object_or_404(ProductAlert, key=kwargs['key'])
        elif 'pk' in kwargs and request.user.is_authenticated():
            self.alert = get_object_or_404(ProductAlert,
                                           user=self.request.user,
                                           pk=kwargs['pk'])
        else:
            raise Http404
        self.update_alert()
        return super(ProductAlertCancelView, self).get(request, *args,
                                                       **kwargs)

    def update_alert(self):
        if self.alert.can_be_cancelled:
            self.alert.cancel()
            messages.success(self.request, _("Your stock alert has been"
                                             " cancelled"))
        else:
            messages.error(self.request, _("Your stock alert cannot be"
                                           " cancelled"))

    def get_redirect_url(self, **kwargs):
        return self.request.GET.get('next',
                                    self.alert.product.get_absolute_url())

apps/dashboard/orders/__init__.py
default_app_config = 'oscar.apps.dashboard.orders.config.OrdersDashboardConfig'

apps/dashboard/orders/app.py
from django.conf.urls import url

from oscar.core.application import Application
from oscar.core.loading import get_class


class OrdersDashboardApplication(Application):
    name = None
    default_permissions = ['is_staff', ]
    permissions_map = {
        'order-list': (['is_staff'], ['partner.dashboard_access']),
        'order-stats': (['is_staff'], ['partner.dashboard_access']),
        'order-detail': (['is_staff'], ['partner.dashboard_access']),
        'order-detail-note': (['is_staff'], ['partner.dashboard_access']),
        'order-line-detail': (['is_staff'], ['partner.dashboard_access']),
        'order-shipping-address': (['is_staff'], ['partner.dashboard_access']),
    }

    order_list_view = get_class('dashboard.orders.views', 'OrderListView')
    order_detail_view = get_class('dashboard.orders.views', 'OrderDetailView')
    shipping_address_view = get_class('dashboard.orders.views',
                                      'ShippingAddressUpdateView')
    line_detail_view = get_class('dashboard.orders.views', 'LineDetailView')
    order_stats_view = get_class('dashboard.orders.views', 'OrderStatsView')

    def get_urls(self):
        urls = [
            url(r'^$', self.order_list_view.as_view(), name='order-list'),
            url(r'^statistics/$', self.order_stats_view.as_view(),
                name='order-stats'),
            url(r'^(?P<number>[-\w]+)/$',
                self.order_detail_view.as_view(), name='order-detail'),
            url(r'^(?P<number>[-\w]+)/notes/(?P<note_id>\d+)/$',
                self.order_detail_view.as_view(), name='order-detail-note'),
            url(r'^(?P<number>[-\w]+)/lines/(?P<line_id>\d+)/$',
                self.line_detail_view.as_view(), name='order-line-detail'),
            url(r'^(?P<number>[-\w]+)/shipping-address/$',
                self.shipping_address_view.as_view(),
                name='order-shipping-address'),
        ]
        return self.post_process_urls(urls)


application = OrdersDashboardApplication()

apps/order/__init__.py
default_app_config = 'oscar.apps.order.config.OrderConfig'

templates/oscar/customer/order/order_detail.html
{% extends "customer/baseaccountpage.html" %}
{% load currency_filters %}
{% load display_tags %}
{% load i18n %}
{% load reviews_tags %}

{% block extra_breadcrumbs %}
    <li>
        <a href="{% url 'customer:order-list' %}">{% trans 'Order history' %}</a>
    </li>
{% endblock %}

{% block tabcontent %}
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>{% trans 'Product' %}</th>
                <th>{% trans 'Dispatch date' %}</th>
                <th>{% trans 'Qty' %}</th>
                <th>{% trans 'Line price excl. tax' %}</th>
                <th>{% trans 'Line price incl. tax' %}</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for line in order.lines.all %}
                {% with product=line.product %}
                    <tr>
                        <td>
                            {% if product %}
                                <p>
                                    <a href="{{ product.get_absolute_url }}">{{ line.description }}</a>
                                </p>
                                {% iffeature "reviews" %}
                                    {% if product|is_review_permitted:user %}
                                        <a class="btn btn-default" href="{% url 'catalogue:reviews-add' product_slug=product.slug product_pk=product.id %}#addreview">{% trans 'Write a review' %}</a>
                                    {% endif %}
                                {% endiffeature %}
                            {% else %}
                                <p>
                                    {{ line.description }}
                                </p>
                            {% endif %}
                        </td>
                        <td>{{ line.est_dispatch_date|default:"-" }}</td>
                        <td>{{ line.quantity }}</td>
                        <td>{{ line.line_price_before_discounts_excl_tax|currency:order.currency }}</td>
                        <td>{{ line.line_price_before_discounts_incl_tax|currency:order.currency }}</td>
                        <td width="90">
                            {% if product %}
                                <form id="line_form_{{ line.id }}" action="{% url 'customer:order-line' order_number=order.number line_id=line.id %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="action" value="reorder" />
                                    <button id="reorder_line_{{ line.id }}" class="btn btn-success" type="submit" data-loading-text="{% trans 'Re-ordering...' %}">{% trans 'Re-order' %}</button>
                                </form>
                            {% else %}
                                {% trans 'Not available anymore' %}
                            {% endif %}
                        </td>
                    </tr>
                {% endwith %}
            {% endfor %}

            {% with discounts=order.basket_discounts %}
                {% block discount_totals %}
                    {% if discounts %}
                        <tr>
                            <td colspan="4">{% trans "Basket total (excl. discounts)" %}</td>
                            <td colspan="2">{{ order.basket_total_before_discounts_incl_tax|currency:order.currency }}</td>
                        </tr>
                        {% for discount in discounts %}
                        <tr>
                            <td colspan="4">
                                <span class="label label-success">{% trans "Discount" %}</span>
                                {{ discount.offer_name }}
                            </td>
                            <td colspan="2">- {{ discount.amount|currency:order.currency }}</td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                {% endblock discount_totals %}

                {% block basket_total %}
                    {% if discounts %}
                        <tr>
                            <th colspan="4">{% trans "Basket total (inc. discounts)" %}</th>
                            <td colspan="2">{{ order.basket_total_incl_tax|currency:order.currency }}</td>
                        </tr>
                    {% else %}
                        <tr>
                            <th colspan="4">{% trans "Basket total" %}</th>
                            <td colspan="2">{{ order.basket_total_incl_tax|currency:order.currency }}</td>
                        </tr>
                    {% endif %}
                {% endblock basket_total %}
            {% endwith %}

            {% block shipping_totals %}
                {% if order.has_shipping_discounts %}
                    <tr>
                        <td colspan="4">{% trans "Shipping total (excl. discounts)" %}</td>
                        <td colspan="2">{{ order.shipping_before_discounts_incl_tax|currency:order.currency }}</td>
                    </tr>
                    {% for discount in order.shipping_discounts %}
                    <tr>
                        <td colspan="4">
                            <span class="label label-success">{% trans "Discount" %}</span>
                            {{ discount.offer_name }}
                        </td>
                        <td colspan="2">- {{ discount.amount|currency:order.currency }}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4">{% trans "Shipping total (inc. discounts)" %}</th>
                        <td colspan="2">{{ order.shipping_incl_tax|currency:order.currency }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <th colspan="4">{% trans "Shipping total" %}</th>
                        <td colspan="2">{{ order.shipping_incl_tax|currency:order.currency }}</td>
                    </tr>
                {% endif %}
            {% endblock %}

            {% block order_total %}
                <tr>
                    <th colspan="4">{% trans 'Order total' %}</th>
                    <td colspan="2">{{ order.total_incl_tax|currency:order.currency }}</td>
                </tr>
            {% endblock order_total %}
        </tbody>
    </table>

    {% block order_actions %}
        <form id="order_form_{{ order.id }}" action="{% url 'customer:order' order_number=order.number %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="order_id" value="{{ order.id }}" />
            <input type="hidden" name="action" value="reorder" />
            <button type="submit" class="btn btn-success" data-loading-text="{% trans 'Re-ordering...' %}">{% trans 'Re-order all items' %}</button>
        </form>
    {% endblock order_actions %}

    <hr>

    <h2>{% trans 'Shipping Method' %}</h2>
    <p>{{ order.shipping_method }}</p>

    <hr>

    <h2>{% trans 'Shipping Address' %}</h2>

    <table class="table table-striped table-bordered">
        <tr>
            <th>{% trans 'Address' %}</th>
            <th>{% trans 'Contact Number' %}</th>
            <th>{% trans 'Shipping Notes' %}</th>
        </tr>
        <tr>
            <td>
                    {% for field in order.shipping_address.active_address_fields %}
                        {{ field }}<br/>
                    {% endfor %}
            </td>
            <td>{{ order.shipping_address.phone_number|default:"-" }}</td>
            <td>{{ order.shipping_address.notes|linebreaks }}</td>
        </tr>
    </table>
{% endblock tabcontent %}

templates/oscar/customer/order/order_list.html
{% extends "customer/baseaccountpage.html" %}
{% load i18n %}
{% load currency_filters %}
{% load staticfiles %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{{ homepage_url }}">{% trans 'Home' %}</a>
        </li>
        <li>
            <a href="{% url 'customer:summary' %}">{% trans 'Account' %}</a>
        </li>
        <li class="active">{% trans 'Order history' %}</li>
    </ul>
{% endblock %}

{% block tabcontent %}

    {% if orders or form.is_bound %}
        <div class="well">
            <h2>{% trans "Filter" %}</h2>
            <form action="." method="get" class="form-horizontal">
                {% include "partials/form_fields.html" with form=form style='horizontal' %}
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-primary" data-loading-text="{% trans 'Filtering...' %}">{% trans 'Filter results' %}</button>
                        <a href="{% url 'customer:order-list' %}" class="btn btn-default">{% trans 'Reset' %}</a>
                    </div>
                </div>
            </form>
        </div>
    {% endif %}

    {% if orders %}
        <h2>{{ form.description }}</h2>
        <table class="table table-striped table-bordered">
            <tr>
                <th>{% trans "Order number" %}</th>
                <th>{% trans "Num items" %}</th>
                <th>{% trans "Total inc tax" %}</th>
                <th>{% trans "Date submitted" %}</th>
            </tr>
            {% for order in orders %}
                <tr>
                    <td><a href="{% url 'customer:order' order_number=order.number %}">{{ order.number }}</a></td>
                    <td>{{ order.num_items }}</td>
                    <td>{{ order.total_incl_tax|currency:order.currency }}</td>
                    <td>{{ order.date_placed }}</td>
                </tr>
            {% endfor %}
        </table>
        {% include "partials/pagination.html" %}
    {% else %}
        {% if form.is_bound %}
            <p>{% trans "No orders match your search." %}</p>
        {% else %}
            <p>{% trans "You haven't placed any orders." %}</p>
        {% endif %}
    {% endif %}

{% endblock tabcontent %}

{% block extrastyles %}
    {{ block.super }}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/cupertino/jquery-ui.css">
{% endblock %}

{% block cdn_scripts %}
    {{ block.super }}
    <script src="//code.jquery.com/ui/1.10.3/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% block onbodyload %}
    {{ block.super }}
    $('#id_date_to, #id_date_from').datepicker({'dateFormat': 'yy-mm-dd'});
{% endblock %}